name: CI

on: [push, pull_request]

jobs:
  python:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    uses: casonk/.github/.github/workflows/python-ci.yml@main
    with:
      python-versions: '["3.11", "3.12"]'
      run-pytest: false

  shell:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    uses: casonk/.github/.github/workflows/shell-ci.yml@main
    with:
      run-tests: false
